package projectUAS;

/**
 *
 * @author ALDII
 */
import java.awt.*;
import java.util.Date;
import java.util.function.*;
import java.text.SimpleDateFormat;
import java.sql.*; 
import java.text.DateFormat;
import java.util.logging.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class EditTiket extends javax.swing.JFrame {
    private int admId;

    /**
     * Creates new form Jframe
     */
    public EditTiket(int admId) {
        initComponents();
        Bersih();
        TdkAktif();
        bioskop_tabel();
        tampilTiket();
        this.setLocationRelativeTo(null);// center form in the screen
        DateFormat dateFormat = new SimpleDateFormat("EEEE, dd MMMMM, yyyy");
        Date date = new Date();
        lblmaindate.setText(dateFormat.format(date));
        
       this.admId= admId;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbFilm = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnUpdate = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_bioskop = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        cmbIdPembelian = new javax.swing.JComboBox<>();
        txtNamaUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtnEdit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        lblmaindate = new javax.swing.JLabel();
        spnrJumlahTiket = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtIdUser = new javax.swing.JTextField();
        cmbWaktu = new javax.swing.JComboBox<>();
        cmbTanggal = new javax.swing.JComboBox<>();
        txtNoBangku = new javax.swing.JTextField();
        chkBoxA1 = new javax.swing.JCheckBox();
        chkBoxA2 = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        chkBoxA3 = new javax.swing.JCheckBox();
        chkBoxA4 = new javax.swing.JCheckBox();
        chkBoxA5 = new javax.swing.JCheckBox();
        chkBoxA6 = new javax.swing.JCheckBox();
        chkBoxA7 = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        chkBoxB3 = new javax.swing.JCheckBox();
        chkBoxB4 = new javax.swing.JCheckBox();
        chkBoxB5 = new javax.swing.JCheckBox();
        chkBoxB6 = new javax.swing.JCheckBox();
        chkBoxB7 = new javax.swing.JCheckBox();
        chkBoxB1 = new javax.swing.JCheckBox();
        chkBoxB2 = new javax.swing.JCheckBox();
        chkBoxC3 = new javax.swing.JCheckBox();
        chkBoxC4 = new javax.swing.JCheckBox();
        chkBoxC5 = new javax.swing.JCheckBox();
        chkBoxC6 = new javax.swing.JCheckBox();
        chkBoxC7 = new javax.swing.JCheckBox();
        chkBoxC1 = new javax.swing.JCheckBox();
        chkBoxC2 = new javax.swing.JCheckBox();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input Tiket Bioskop");

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Nomor Tiket");

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Judul Film");

        cmbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".:Pilih:." }));
        cmbFilm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbFilm.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbFilmPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilmActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Total Bayar");

        BtnUpdate.setMnemonic('T');
        BtnUpdate.setText("Update");
        BtnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnHapus.setMnemonic('S');
        BtnHapus.setText("Hapus");
        BtnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Batal");
        BtnBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        tb_bioskop.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tb_bioskop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", null, null, null, null},
                {null, null, "", null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane3.setViewportView(tb_bioskop);

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Jumlah Tiket");

        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Tanggal ");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADMIN");

        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        cmbIdPembelian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".:Pilih:." }));
        cmbIdPembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbIdPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdPembelianActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Nama Pemesan");

        BtnEdit.setText("Edit");
        BtnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 0));
        jLabel10.setText("EDIT TIKET ");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Waktu");

        lblmaindate.setForeground(new java.awt.Color(255, 0, 0));
        lblmaindate.setText(" ");

        spnrJumlahTiket.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID USER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        txtIdUser.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        txtIdUser.setForeground(new java.awt.Color(255, 51, 51));
        txtIdUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdUser.setText("ID_USER");

        cmbWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".:Pilih:.", "10:00", "12:30", "15:00", "17:30", "20:00" }));
        cmbWaktu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbWaktu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbWaktuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWaktuActionPerformed(evt);
            }
        });

        cmbTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".:Pilih:.", "Kamis, 21 Desember 2023", "Jumat, 22 Desember 2023", "Sabtu, 23 Desember 2023", "Minggu, 24 Desember 2023", "Senin, 25 Desember 2023", "Selasa, 26 Desember 2023", "Rabu, 27 Desember 2023", "Kamis, 28 Desember 2023", "Jumat, 29 Desember 2023", "Sabtu, 30 Desember 2023", "Minggu, 31 Desember 2023" }));
        cmbTanggal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbTanggal.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbTanggalPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTanggalActionPerformed(evt);
            }
        });

        chkBoxA1.setText("A1");

        chkBoxA2.setText("A2");

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        chkBoxA3.setText("A3");

        chkBoxA4.setText("A4");

        chkBoxA5.setText("A5");

        chkBoxA6.setText("A6");

        chkBoxA7.setText("A7");

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("No Bangku");

        chkBoxB3.setText("B3");

        chkBoxB4.setText("B4");

        chkBoxB5.setText("B5");

        chkBoxB6.setText("B6");

        chkBoxB7.setText("B7");

        chkBoxB1.setText("B1");

        chkBoxB2.setText("B2");

        chkBoxC3.setText("C3");

        chkBoxC4.setText("C4");

        chkBoxC5.setText("C5");

        chkBoxC6.setText("C6");

        chkBoxC7.setText("C7");

        chkBoxC1.setText("C1");
        chkBoxC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxC1ActionPerformed(evt);
            }
        });

        chkBoxC2.setText("C2");
        chkBoxC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxC2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("*");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("*");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("*");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("*");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnrJumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(81, 81, 81)
                                .addComponent(cmbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtNoBangku, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkBoxC1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkBoxC2)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkBoxC3)
                                        .addGap(12, 12, 12)
                                        .addComponent(chkBoxC4)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkBoxC5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkBoxC6)
                                        .addGap(12, 12, 12)
                                        .addComponent(chkBoxC7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkBoxB1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chkBoxB2)
                                                .addGap(18, 18, 18)
                                                .addComponent(chkBoxB3)
                                                .addGap(12, 12, 12)
                                                .addComponent(chkBoxB4)
                                                .addGap(18, 18, 18)
                                                .addComponent(chkBoxB5)
                                                .addGap(12, 12, 12)
                                                .addComponent(chkBoxB6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkBoxA1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chkBoxA2)
                                                .addGap(18, 18, 18)
                                                .addComponent(chkBoxA3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chkBoxA4)
                                                .addGap(18, 18, 18)
                                                .addComponent(chkBoxA5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chkBoxA6)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(chkBoxB7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkBoxA7))))))
                            .addComponent(BtnKeluar)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 85, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtnEdit)
                        .addGap(32, 32, 32)
                        .addComponent(BtnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal)
                        .addGap(50, 50, 50)
                        .addComponent(BtnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(654, 654, 654)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(654, 654, 654)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmaindate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 91, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblmaindate))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbIdPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel19))
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(cmbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel15))))))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtNoBangku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spnrJumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBoxA1)
                                    .addComponent(chkBoxA2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkBoxA6)
                                        .addComponent(chkBoxA7)
                                        .addComponent(chkBoxA5)
                                        .addComponent(chkBoxA4)
                                        .addComponent(chkBoxA3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBoxB1)
                                    .addComponent(chkBoxB2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkBoxB5)
                                        .addComponent(chkBoxB4)
                                        .addComponent(chkBoxB6)
                                        .addComponent(chkBoxB7)
                                        .addComponent(chkBoxB3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBoxC1)
                                    .addComponent(chkBoxC2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkBoxC5)
                                        .addComponent(chkBoxC4)
                                        .addComponent(chkBoxC6)
                                        .addComponent(chkBoxC7)
                                        .addComponent(chkBoxC3)))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnEdit)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnBatal)
                                .addComponent(BtnUpdate))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnKeluar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnHapus)))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilmActionPerformed
        try {

           String sql = "SELECT judul FROM film";
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con = KoneksiDB.getKoneksi();
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);

           while (rs.next()) {
               String judulFilm = rs.getString("judul");
               // Check if the item is already present before adding
               if (!itemExists(cmbFilm, judulFilm)) {
                   cmbFilm.addItem(judulFilm);
               }
           }
       } catch (Exception ex) {
           cmbFilm.addItem(".:Pilih::.");
       }
    }//GEN-LAST:event_cmbFilmActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
         Aktif();
        cmbIdPembelian.requestFocus();    

        try {
            // Get the selected id_pembelian
            String nomorTiket = cmbIdPembelian.getSelectedItem().toString();

            // Retrieve id_user from the selected item in cmbIdPembelian
            String idUser = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = KoneksiDB.getKoneksi();
            String getIdUserSQL = "SELECT id_user FROM pembelian WHERE id_pembelian=?";
            try (PreparedStatement getIdUserStatement = con.prepareStatement(getIdUserSQL)) {
                getIdUserStatement.setString(1, nomorTiket);
                ResultSet getIdUserResultSet = getIdUserStatement.executeQuery();
                if (getIdUserResultSet.next()) {
                    idUser = getIdUserResultSet.getString("id_user");
                }
            }

            // Now you can use idUser in your SQL query
            String judulFilm = cmbFilm.getSelectedItem().toString();
            String tanggal = cmbTanggal.getSelectedItem().toString();
            String waktu = cmbWaktu.getSelectedItem().toString();
            String hargaTiket = txtTotalBayar.getText();
            String nomorBangku = txtNoBangku.getText();

            int jumlahTiket = (int) spnrJumlahTiket.getValue();

            // Update the SQL query to include id_user
            String sql = "UPDATE pembelian SET id_user=?, film=?, tanggal=?, waktu=?, jumlah_tiket=?, total_bayar=?, no_bangku=? WHERE id_pembelian=?";
            try (PreparedStatement updateStatement = con.prepareStatement(sql)) {
                updateStatement.setString(1, idUser);
                updateStatement.setString(2, judulFilm);
                updateStatement.setString(3, tanggal);
                updateStatement.setString(4, waktu);
                updateStatement.setInt(5, jumlahTiket);
                updateStatement.setString(6, hargaTiket);
                updateStatement.setString(7, nomorBangku);
                updateStatement.setString(8, nomorTiket);

                updateStatement.executeUpdate();
            }

            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(null, "Data sudah diupdate", "Update", JOptionPane.INFORMATION_MESSAGE);
            });

            bioskop_tabel();
            Bersih();
            TdkAktif();
        } catch (SQLException | ClassNotFoundException e) {
            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(null, "Ada kesalahan dalam mengupdate data pada :" + e, "Error", JOptionPane.ERROR_MESSAGE);
            });
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
      Object idPembelian = cmbIdPembelian.getSelectedItem();
        String id = idPembelian.toString();
        int ok = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus \n tiket dengan id : "+id+"","Konfirmasi Tiket", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = KoneksiDB.getKoneksi();
                String sql = "DELETE FROM pembelian WHERE id_pembelian='"+id+"'";
                Statement stm = con.createStatement();
                int status = stm.executeUpdate(sql);
                if (status>=0){
                    JOptionPane.showMessageDialog(null, "Hapus Tiket Berhasil !", "Sukses", JOptionPane.OK_OPTION);
                    bioskop_tabel();
                }else{
                    JOptionPane.showMessageDialog(null, "Gagal Hapus Tiket", "Simpan", JOptionPane.ERROR_MESSAGE);
                }
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "Ada Kesalahan Dalam Hapus Data, \nError"+ ex.getMessage(), "SImpan", JOptionPane.ERROR_MESSAGE);
                }catch(ClassNotFoundException ex){
                    Logger.getLogger(EditTiket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        Bersih();
        TdkAktif();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void cmbFilmPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbFilmPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_cmbFilmPopupMenuWillBecomeInvisible

    private void cmbWaktuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbWaktuPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbWaktuPopupMenuWillBecomeInvisible

    private void cmbWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbWaktuActionPerformed

    private void cmbTanggalPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbTanggalPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTanggalPopupMenuWillBecomeInvisible

    private void cmbTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTanggalActionPerformed

    private void cmbIdPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdPembelianActionPerformed
            try {
            String id = "", id_user = "", nama_pemesan = "", film = "", tanggal = "", waktu = "", bangku = "", bayar = "";
            int jml_tiket = 0;
            Object id_pembelian = cmbIdPembelian.getSelectedItem();//ambil isi pada combo
            id = id_pembelian.toString();
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = KoneksiDB.getKoneksi();
            String sql = "SELECT id_user, nm_depan, nm_belakang, film, tanggal, waktu, jumlah_tiket, total_bayar, no_bangku "
                        + "FROM pembelian "
                        + "JOIN user ON pembelian.id_user= user.id "
                        + "WHERE id_pembelian='" + id + "'";

            Statement st = con.createStatement();

            //set pointer rs untuk membaca jika sama dengan yang kita pilih dari combo
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                id_user = rs.getString("id_user");
                nama_pemesan = rs.getString("nm_depan") + " " + rs.getString("nm_belakang");
                film = rs.getString("film");
                tanggal = rs.getString("tanggal");
                waktu = rs.getString("waktu");
                jml_tiket = rs.getInt("jumlah_tiket");
                bayar = rs.getString("total_bayar");
                bangku = rs.getString("no_bangku");
            }
            txtIdUser.setText(id_user);
            txtNamaUser.setText(nama_pemesan);
            cmbFilm.setSelectedItem(film);
            cmbTanggal.setSelectedItem(tanggal);
            cmbWaktu.setSelectedItem(waktu);
            spnrJumlahTiket.setValue(jml_tiket);
            txtTotalBayar.setText(bayar);
            txtNoBangku.setText(bangku);
            cmbIdPembelian.requestFocus();
        } catch (Exception e) {
            // Handle exceptions appropriately (e.g., log or show an error message)
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbIdPembelianActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        Aktif();// TODO add your handling code here:
    }//GEN-LAST:event_BtnEditActionPerformed

    private void chkBoxC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxC1ActionPerformed

    private void chkBoxC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxC2ActionPerformed

    
        public void Bersih() {
            cmbIdPembelian.setSelectedItem(".:Pilih:.");
            txtNamaUser.setText("");
            cmbFilm.setSelectedItem(".:Pilih:.");
            cmbTanggal.setSelectedItem(".:Pilih:.");
            cmbWaktu.setSelectedItem(".:Pilih:.");
            spnrJumlahTiket.setValue(0);
            txtTotalBayar.setText("");
            txtNoBangku.setText("");
            txtIdUser.setText("");
        }
        public void Aktif(){
            cmbIdPembelian.setEnabled(true);
            cmbFilm.setEnabled(true);
            cmbTanggal.setEnabled(true);
            cmbWaktu.setEnabled(true);
            BtnHapus.setEnabled(true);
            BtnUpdate.setEnabled(true);
            BtnBatal.setEnabled(true);
        }
        
        public final void TdkAktif(){
            txtNamaUser.setEditable(false);
            cmbFilm.setEnabled(false);
            cmbTanggal.setEnabled(false);
            cmbWaktu.setEnabled(false);
            spnrJumlahTiket.setEnabled(false);
            txtTotalBayar.setEditable(false);
            txtNoBangku.setEditable(false);
            txtIdUser.setEditable(false);
            BtnHapus.setEnabled(false);
            BtnUpdate.setEnabled(false);
            BtnBatal.setEnabled(false);
        }
        
        private void bioskop_tabel(){
            try{
                Connection con = KoneksiDB.getKoneksi();
                String sql = "SELECT id_pembelian, film, tanggal, waktu, jumlah_tiket, total_bayar, no_bangku " +
                             "FROM pembelian " +
                             "JOIN user ON pembelian.id_user = user.id";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                //System.out.print(rs);
                tb_bioskop.setModel(DbUtils.resultSetToTableModel(rs)); 
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        
        private void tampilTiket() {
        try {
            String sql = "SELECT * FROM pembelian";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = KoneksiDB.getKoneksi();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) 
            {
                String idPembelian = rs.getString("id_pembelian");
                cmbIdPembelian.addItem(idPembelian);
            }
        } catch (Exception ex) {
            cmbIdPembelian.addItem(".:Pilih::.");
        }
    }
        // Helper method to check if an item exists in the combo box
    private boolean itemExists(javax.swing.JComboBox<String> comboBox, String item) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (comboBox.getItemAt(i).equals(item)) {
                return true;
            }
        }
        return false;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        int admId = 0;

        if (admId <= 0) {
            JOptionPane.showMessageDialog(null, "Anda harus Login terlebih dahulu.\nMengalihkan ke form login!");

            // Redirect to the index form
            index indexForm = new index();
            indexForm.setVisible(true);
            
            // Open Login form
            Admin adminForm = new Admin();
            adminForm.setVisible(true);
            
        } else {
            // Show the TiketBioskop form for the specified userId
            EditTiket editTiket = new EditTiket(admId);
            editTiket.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JCheckBox chkBoxA1;
    private javax.swing.JCheckBox chkBoxA2;
    private javax.swing.JCheckBox chkBoxA3;
    private javax.swing.JCheckBox chkBoxA4;
    private javax.swing.JCheckBox chkBoxA5;
    private javax.swing.JCheckBox chkBoxA6;
    private javax.swing.JCheckBox chkBoxA7;
    private javax.swing.JCheckBox chkBoxB1;
    private javax.swing.JCheckBox chkBoxB2;
    private javax.swing.JCheckBox chkBoxB3;
    private javax.swing.JCheckBox chkBoxB4;
    private javax.swing.JCheckBox chkBoxB5;
    private javax.swing.JCheckBox chkBoxB6;
    private javax.swing.JCheckBox chkBoxB7;
    private javax.swing.JCheckBox chkBoxC1;
    private javax.swing.JCheckBox chkBoxC2;
    private javax.swing.JCheckBox chkBoxC3;
    private javax.swing.JCheckBox chkBoxC4;
    private javax.swing.JCheckBox chkBoxC5;
    private javax.swing.JCheckBox chkBoxC6;
    private javax.swing.JCheckBox chkBoxC7;
    private javax.swing.JComboBox<String> cmbFilm;
    private javax.swing.JComboBox<String> cmbIdPembelian;
    private javax.swing.JComboBox<String> cmbTanggal;
    private javax.swing.JComboBox<String> cmbWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblmaindate;
    private javax.swing.JSpinner spnrJumlahTiket;
    private javax.swing.JTable tb_bioskop;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JTextField txtNoBangku;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables

}