/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectUAS;

import projectUAS.*;
import java.awt.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author ALDII
 */
public class index extends javax.swing.JFrame {
    private static final String DB_URL = "jdbc:mysql://localhost:3306/db_tiketbioskop";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "";
    
    private JLabel[] filmLabels;
    private JLabel[] filmPosters;
    
    public index() {
        initComponents();
        initializeFilmComponents();
        this.setLocationRelativeTo(null);// center form in the screen
        setTitle("Cinema Indo");
        populateFilmData();
    }
    
     private void initializeFilmComponents() {
        filmLabels = new JLabel[]{label_film1, label_film2, label_film3, label_film4};
        filmPosters = new JLabel[]{poster_film1, poster_film2, poster_film3, poster_film4};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        poster_film1 = new javax.swing.JLabel();
        poster_film2 = new javax.swing.JLabel();
        poster_film3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_film1 = new javax.swing.JLabel();
        label_film2 = new javax.swing.JLabel();
        label_film3 = new javax.swing.JLabel();
        pesan = new javax.swing.JButton();
        poster_film4 = new javax.swing.JLabel();
        label_film4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 970, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Daftar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 120, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Masuk");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 110, 40));

        poster_film1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oppenheimer.jpg"))); // NOI18N
        poster_film1.setText("poster1");
        poster_film1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster_film1MouseClicked(evt);
            }
        });
        poster_film1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                poster_film1PropertyChange(evt);
            }
        });
        getContentPane().add(poster_film1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, 280));

        poster_film2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barbie.jpg"))); // NOI18N
        poster_film2.setText("poster2");
        poster_film2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster_film2MouseClicked(evt);
            }
        });
        getContentPane().add(poster_film2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, 280));

        poster_film3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thekiller.jpg"))); // NOI18N
        poster_film3.setText("poster3");
        poster_film3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster_film3MouseClicked(evt);
            }
        });
        getContentPane().add(poster_film3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 190, 280));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("SEDANG TAYANG");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        label_film1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_film1.setText("Oppenheimer");
        label_film1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_film1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                label_film1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        label_film1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_film1MouseClicked(evt);
            }
        });
        getContentPane().add(label_film1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        label_film2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_film2.setText("Barbie");
        label_film2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_film2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                label_film2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        label_film2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_film2MouseClicked(evt);
            }
        });
        getContentPane().add(label_film2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        label_film3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_film3.setText("The Killer");
        label_film3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_film3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                label_film3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        label_film3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_film3MouseClicked(evt);
            }
        });
        getContentPane().add(label_film3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, -1));

        pesan.setBackground(new java.awt.Color(0, 204, 51));
        pesan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pesan.setForeground(new java.awt.Color(255, 255, 255));
        pesan.setText("Pesan Tiket");
        pesan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        getContentPane().add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 140, 40));

        poster_film4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/napoleon.jpg"))); // NOI18N
        poster_film4.setText("poster4");
        poster_film4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poster_film4MouseClicked(evt);
            }
        });
        getContentPane().add(poster_film4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 190, 280));

        label_film4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        label_film4.setText("Napoleon");
        label_film4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_film4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                label_film4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        label_film4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_film4MouseClicked(evt);
            }
        });
        getContentPane().add(label_film4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, -1, 20));

        jPanel1.setBackground(new java.awt.Color(178, 53, 53));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cinema INDO");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        admin.setBackground(new java.awt.Color(0, 178, 178));
        admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("ADMIN");
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(384, 384, 384))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 170));

        setBounds(0, 0, 1055, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void label_film1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_film1MouseClicked

    }//GEN-LAST:event_label_film1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Register rgs = new Register();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
//        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void label_film2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_film2MouseClicked
        
    }//GEN-LAST:event_label_film2MouseClicked

    private void label_film3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_film3MouseClicked

    }//GEN-LAST:event_label_film3MouseClicked

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Anda harus login dulu !");
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_pesanActionPerformed

    private void label_film4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_film4MouseClicked

    }//GEN-LAST:event_label_film4MouseClicked

    private void poster_film1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster_film1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_poster_film1MouseClicked

    private void poster_film2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster_film2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_poster_film2MouseClicked

    private void poster_film3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster_film3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_poster_film3MouseClicked

    private void poster_film4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poster_film4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_poster_film4MouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
            
    }//GEN-LAST:event_formWindowStateChanged

    private void label_film1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_label_film1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_label_film1AncestorAdded

    private void label_film2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_label_film2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_label_film2AncestorAdded

    private void label_film3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_label_film3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_label_film3AncestorAdded

    private void label_film4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_label_film4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_label_film4AncestorAdded

    private void poster_film1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_poster_film1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_poster_film1PropertyChange

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ini adalah Dashboard Admin");
        Admin log = new Admin();
        log.setVisible(true);
    }//GEN-LAST:event_adminActionPerformed
    private void populateFilmData() {
     try (Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String query = "SELECT judul, poster_film, sinopsis FROM film";
            try (PreparedStatement statement = connection.prepareStatement(query);
                ResultSet resultSet = statement.executeQuery()) {

                int filmIndex = 0;
                while (resultSet.next() && filmIndex < filmLabels.length) {
                    String labelFilm = resultSet.getString("judul");
                    String posterFilmPath = resultSet.getString("poster_film");
                    String sinopsis = resultSet.getString("sinopsis").replace("\\n", "\n");

                    filmLabels[filmIndex].setText(labelFilm);

                    ImageIcon posterIcon = new ImageIcon(getClass().getResource("/images/" + posterFilmPath));
                    filmPosters[filmIndex].setIcon(posterIcon);

                    filmPosters[filmIndex].addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            JOptionPane.showMessageDialog(null, "Sinopsis: " + sinopsis);
                        }
                    });

                    filmIndex++;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new index().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel label_film1;
    private javax.swing.JLabel label_film2;
    private javax.swing.JLabel label_film3;
    private javax.swing.JLabel label_film4;
    private javax.swing.JButton pesan;
    private javax.swing.JLabel poster_film1;
    private javax.swing.JLabel poster_film2;
    private javax.swing.JLabel poster_film3;
    private javax.swing.JLabel poster_film4;
    // End of variables declaration//GEN-END:variables
// Add a method to get component by name
    private javax.swing.JComponent getComponentByName(String name) {
       for (java.awt.Component comp : getContentPane().getComponents()) {
           if (comp.getName() != null && comp.getName().equals(name)) {
               return (javax.swing.JComponent) comp;
           }
       }
       System.out.println("Component not found for name: " + name); // Add this line for debugging
       return null;
   }
}