/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectUAS;

import java.awt.*;
import java.util.Date;
import java.util.function.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.*;
import java.io.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;

/**
 *
 * @author ACER
 */
public class TiketBioskop extends javax.swing.JFrame {
    String [][] purchasesave = new String [5][1];
    double overralltotalsale = 0;
    int jumlahTiket = 0;
    int ps =0;
    String password;
    String cekpassword = "kosonginaja";
    private int userId;
    private Map<String, JCheckBox> seatCheckboxMap;
    private int jumlahCheckBox = 0; // Added variable to store the quantity of checkboxes selected
    private int purchaseIdCounter = 1; // Add this variable to keep track of the incrementing number
    
    /**
     * Creates new form TiketBioskop
     */
     public TiketBioskop(int userId) {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen
        DateFormat dateFormat = new SimpleDateFormat("EEEE, dd MMMMM, yyyy");
        Date date = new Date();
        lblmaindate.setText(dateFormat.format(date));
        initializeSeatCheckboxMap();
        //user loggin data
        this.userId = userId;
    }
     

    private String generatePurchaseId() {
    // Construct the final purchase ID with the user ID as a prefix
    String purchaseId = "U" + userId + "P" + purchaseIdCounter;

    // Increment the counter for the next purchase
    purchaseIdCounter++;

    return purchaseId;
}
    
    private void resetPurchaseIdCounter() {
    purchaseIdCounter = 1;
    }

    // Call this method when a new user logs in
    private void handleNewUserLogin() {
        resetPurchaseIdCounter();
        // Other initialization code for the new user
    }
    
// Add this method to count available chairs
private int countAvailableChairs() {
    int totalChairs = 21;
    int enableChairs = 21;

    // Add all your checkboxes to this array
    JCheckBox[] checkboxes = {chkBoxA1, chkBoxA2, chkBoxA3, chkBoxA4, chkBoxA5, chkBoxA6, chkBoxA7,
            chkBoxB1, chkBoxB2, chkBoxB3, chkBoxB4, chkBoxB5, chkBoxB6, chkBoxB7,
            chkBoxC1, chkBoxC2, chkBoxC3, chkBoxC4, chkBoxC5, chkBoxC6, chkBoxC7};

    for (JCheckBox checkbox : checkboxes) {
        if (!checkbox.isSelected() && checkbox.isEnabled()) {
            totalChairs--;
        }
    }

    enableChairs -= totalChairs;

    return enableChairs;
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTagihan = new javax.swing.JButton();
        lblmaindate = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblPajak = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        btnBaru = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnDetailPembelian = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNamaFilm = new javax.swing.JLabel();
        lblJumNo = new javax.swing.JLabel();
        lblTgldanWaktu = new javax.swing.JLabel();
        lblTotalBayar = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        chkBoxA1 = new javax.swing.JCheckBox();
        chkBoxA2 = new javax.swing.JCheckBox();
        chkBoxA3 = new javax.swing.JCheckBox();
        chkBoxA4 = new javax.swing.JCheckBox();
        chkBoxA5 = new javax.swing.JCheckBox();
        chkBoxA6 = new javax.swing.JCheckBox();
        chkBoxA7 = new javax.swing.JCheckBox();
        chkBoxB1 = new javax.swing.JCheckBox();
        chkBoxB3 = new javax.swing.JCheckBox();
        chkBoxB4 = new javax.swing.JCheckBox();
        chkBoxB2 = new javax.swing.JCheckBox();
        chkBoxB5 = new javax.swing.JCheckBox();
        chkBoxB7 = new javax.swing.JCheckBox();
        chkBoxB6 = new javax.swing.JCheckBox();
        chkBoxC2 = new javax.swing.JCheckBox();
        chkBoxC1 = new javax.swing.JCheckBox();
        chkBoxC3 = new javax.swing.JCheckBox();
        chkBoxC5 = new javax.swing.JCheckBox();
        chkBoxC4 = new javax.swing.JCheckBox();
        chkBoxC6 = new javax.swing.JCheckBox();
        chkBoxC7 = new javax.swing.JCheckBox();
        BtnCek = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblbayar = new javax.swing.JLabel();
        lbljumlahkursi = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTanggal = new javax.swing.JComboBox<>();
        cmbWaktu = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbfilm = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTagihan.setText("Tagihan");
        btnTagihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagihanActionPerformed(evt);
            }
        });
        getContentPane().add(btnTagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 1786, -1, -1));

        lblmaindate.setForeground(new java.awt.Color(255, 0, 0));
        lblmaindate.setText(" ");
        getContentPane().add(lblmaindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 107, 178, -1));

        jLabel12.setText("Sub-Total");

        jLabel10.setText("Pajak (2%)");

        jLabel17.setText("Total");

        lblPajak.setText("0");

        lblTotal.setText("0");

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Pilih Kursi dan Jumlah Tiket");

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        btnBaru.setText("Baru");
        btnBaru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnDetailPembelian.setText("Beli");
        btnDetailPembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetailPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailPembelianActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak Tiket");
        btnCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel15.setText("Nama Film");

        jLabel16.setText("Jumlah Tiket | No Bangku");

        jLabel14.setText("Tanggal dan Waktu");

        jLabel11.setText("Total Bayar");

        lblNamaFilm.setText("-");

        lblJumNo.setText("-");

        lblTgldanWaktu.setText("-");

        lblTotalBayar.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(101, 101, 101)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTgldanWaktu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(lblTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblJumNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNamaFilm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNamaFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJumNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTgldanWaktu)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTotalBayar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Buat Pesanan Tiket");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnBaru)
                        .addGap(18, 18, 18)
                        .addComponent(btnHitung)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetailPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCetak)
                        .addGap(59, 59, 59)
                        .addComponent(btnexit))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru)
                    .addComponent(btnHitung)
                    .addComponent(btnDetailPembelian)
                    .addComponent(btnCetak)
                    .addComponent(btnexit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        chkBoxA1.setText("A1");
        chkBoxA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxA1ActionPerformed(evt);
            }
        });

        chkBoxA2.setText("A2");
        chkBoxA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxA2ActionPerformed(evt);
            }
        });

        chkBoxA3.setText("A3");
        chkBoxA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxA3ActionPerformed(evt);
            }
        });

        chkBoxA4.setText("A4");
        chkBoxA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxA4ActionPerformed(evt);
            }
        });

        chkBoxA5.setText("A5");

        chkBoxA6.setText("A6");

        chkBoxA7.setText("A7");

        chkBoxB1.setText("B1");

        chkBoxB3.setText("B3");

        chkBoxB4.setText("B4");
        chkBoxB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxB4ActionPerformed(evt);
            }
        });

        chkBoxB2.setText("B2");

        chkBoxB5.setText("B5");

        chkBoxB7.setText("B7");

        chkBoxB6.setText("B6");

        chkBoxC2.setText("C2");

        chkBoxC1.setText("C1");

        chkBoxC3.setText("C3");

        chkBoxC5.setText("C5");
        chkBoxC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxC5ActionPerformed(evt);
            }
        });

        chkBoxC4.setText("C4");

        chkBoxC6.setText("C6");
        chkBoxC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxC6ActionPerformed(evt);
            }
        });

        chkBoxC7.setText("C7");
        chkBoxC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxC7ActionPerformed(evt);
            }
        });

        BtnCek.setBackground(new java.awt.Color(153, 51, 0));
        BtnCek.setForeground(new java.awt.Color(255, 255, 255));
        BtnCek.setText("Cek Kursi");
        BtnCek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCekActionPerformed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*cek apakah kursi masih tersedia");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Kursi Tersedia :");

        lblbayar.setText("0");

        lbljumlahkursi.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(chkBoxA1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkBoxA2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkBoxA3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(chkBoxC1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkBoxC2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(chkBoxB1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkBoxB2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkBoxB3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkBoxC3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(chkBoxA4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkBoxA5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkBoxA6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(chkBoxC4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                            .addComponent(chkBoxB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(chkBoxC5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkBoxC6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkBoxB5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chkBoxB6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBoxB7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkBoxC7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkBoxA7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(BtnCek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbljumlahkursi, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel17)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPajak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(lblbayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(lblbayar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lblPajak))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(lblTotal)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnCek)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(lbljumlahkursi))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBoxA1)
                            .addComponent(chkBoxA2)
                            .addComponent(chkBoxA3)
                            .addComponent(chkBoxA4)
                            .addComponent(chkBoxA5)
                            .addComponent(chkBoxA6)
                            .addComponent(chkBoxA7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBoxB1)
                            .addComponent(chkBoxB2)
                            .addComponent(chkBoxB3)
                            .addComponent(chkBoxB4)
                            .addComponent(chkBoxB5)
                            .addComponent(chkBoxB6)
                            .addComponent(chkBoxB7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBoxC1)
                            .addComponent(chkBoxC2)
                            .addComponent(chkBoxC3)
                            .addComponent(chkBoxC4)
                            .addComponent(chkBoxC5)
                            .addComponent(chkBoxC6)
                            .addComponent(chkBoxC7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 261, -1, -1));

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Tanggal dan Waktu");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setText("Tanggal Tonton :");

        jLabel4.setText("Waktu Tonton : ");

        cmbTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kamis, 21 Desember 2023", "Jumat, 22 Desember 2023", "Sabtu, 23 Desember 2023", "Minggu, 24 Desember 2023", "Senin, 25 Desember 2023", "Selasa, 26 Desember 2023", "Rabu, 27 Desember 2023", "Kamis, 28 Desember 2023", "Jumat, 29 Desember 2023", "Sabtu, 30 Desember 2023", "Minggu, 31 Desember 2023", "Senin, 1 Januari 2024", "Selasa, 2 Januari 2024", "Rabu, 3 Januari 2024", "Kamis, 4 Januari 2024", "Jumat, 5 Januari 2024", "Sabtu, 6 Januari 2024", "Minggu, 7 Januari 2024", "Senin, 8 Januari 2024", "Selasa, 9 Januari 2024", "Rabu, 10 Januari 2024" }));
        cmbTanggal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "12:30", "15:00", "17:30", "20:00" }));
        cmbWaktu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 280, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cmbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 171, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oppenheimer.jpg"))); // NOI18N
        lblimage.setText(" ");
        lblimage.setMaximumSize(new java.awt.Dimension(200, 300));
        lblimage.setMinimumSize(new java.awt.Dimension(200, 300));
        lblimage.setPreferredSize(new java.awt.Dimension(200, 300));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 126, 195, 300));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1331, 134, 1, 19));

        jPanel5.setBackground(new java.awt.Color(178, 53, 53));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cinema INDO");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel9)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("BELI TIKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Film");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 143, 100, -1));

        cmbfilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oppenheimer", "Barbie", "The Killer", "Napoleon" }));
        cmbfilm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbfilmActionPerformed(evt);
            }
        });
        getContentPane().add(cmbfilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 143, 200, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("TIKET : IDR 40.000/S");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        setBounds(0, 0, 939, 701);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbfilmActionPerformed
        // TODO add your handling code here:
        if((String)cmbfilm.getSelectedItem() == "Oppenheimer"){
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oppenheimer.jpg")));
        }
        else if((String)cmbfilm.getSelectedItem() == "Barbie"){
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barbie.jpg")));    
        }
        else if((String)cmbfilm.getSelectedItem() == "The Killer"){
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thekiller.jpg"))); 
        }
        else{
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/napoleon.jpg")));
        }
        
    }//GEN-LAST:event_cmbfilmActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        final double tiket = 40000;
        double subtotal = 0;
        double pajak = 0;
        double total = 0;

        DecimalFormat formatter = new DecimalFormat("Rp #,##0");

        // Calculate the subtotal based on the selected seats
        int jumlahTiket = 0;
        
        char[] seatLetters = {'A', 'B', 'C'};
        int[] seatNumbers = {1, 2, 3, 4, 5, 6, 7};

       Function<String, JCheckBox> getCheckBox = seat -> {
        switch (seat) {
            case "A1":
                return chkBoxA1;
            case "A2":
                return chkBoxA2;
            case "A3":
                return chkBoxA3;
            case "A4":
                return chkBoxA4;
            case "A5":
                return chkBoxA5;
            case "A6":
                return chkBoxA6;
            case "A7":
                return chkBoxA7;
            case "B1":
                return chkBoxB1;
            case "B2":
                return chkBoxB2;
            case "B3":
                return chkBoxB3;
            case "B4":
                return chkBoxB4;
            case "B5":
                return chkBoxB5;
            case "B6":
                return chkBoxB6;
            case "B7":
                return chkBoxB7;
            case "C1":
                return chkBoxC1;
            case "C2":
                return chkBoxC2;
            case "C3":
                return chkBoxC3;
            case "C4":
                return chkBoxC4;
            case "C5":
                return chkBoxC5;
            case "C6":
                return chkBoxC6;
            case "C7":
                return chkBoxC7;
            default:
                return null;
        }   
    };

        for (char letter : seatLetters) {
            for (int number : seatNumbers) {
                String seat = String.format("%c%d", letter, number);
                JCheckBox checkBox = getCheckBox.apply(seat);

                if (checkBox != null && checkBox.isSelected()) {
                    subtotal += tiket;
                    jumlahTiket++;
                }
            }
        }

        System.out.println("Subtotal before formatting: " + subtotal); // Add this line to print subtotal
        pajak = 0.02 * subtotal;
        total = pajak + subtotal;
        
        lblbayar.setText(formatter.format(subtotal));
        System.out.println("Subtotal after formatting: " + lblbayar.getText());
       
        lblPajak.setText(formatter.format(pajak));
        lblTotal.setText(formatter.format(total));

        overralltotalsale = overralltotalsale + total;
        this.jumlahTiket = jumlahTiket;

    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnDetailPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailPembelianActionPerformed
        // TODO add your handling code here:
        // Count the selected checkboxes
        jumlahCheckBox = countSelectedCheckboxes();

        // Get the selected checkbox text
        String selectedCheckboxText = getSelectedCheckboxText();

        lblNamaFilm.setText((String)cmbfilm.getSelectedItem());
        lblJumNo.setText(jumlahCheckBox + " | " + selectedCheckboxText);
        lblTgldanWaktu.setText((String)cmbTanggal.getSelectedItem() + " | " + (String)cmbWaktu.getSelectedItem());
        lblTotalBayar.setText(lblTotal.getText());

        purchasesave[0][0] = "Nama Film: " + (String)cmbfilm.getSelectedItem();
        purchasesave[1][0] = "Jumlah Tiket | No. Kursi: " + jumlahCheckBox + " | " + selectedCheckboxText;
        purchasesave[2][0] = "Tanggal dan Waktu: " + (String)cmbTanggal.getSelectedItem() + " | " + (String)cmbWaktu.getSelectedItem();
        purchasesave[3][0] = "Total Bayar: " + lblTotal.getText();

        try {
            Connection conn = KoneksiDB.getKoneksi();

            String sql = "INSERT INTO pembelian (id_pembelian, id_user, film, tanggal, waktu, jumlah_tiket, total_bayar, no_bangku) VALUES (?,?,?,?,?,?,?,?)";

            PreparedStatement p = conn.prepareStatement(sql);

            // Use the method to generate purchase ID
            p.setString(1, generatePurchaseId());
            p.setInt(2, userId);
            p.setString(3, (String)cmbfilm.getSelectedItem());
            p.setString(4, (String)cmbTanggal.getSelectedItem());
            p.setString(5, (String)cmbWaktu.getSelectedItem());
            p.setInt(6, jumlahCheckBox);
            p.setString(7, lblTotal.getText());
            p.setString(8, selectedCheckboxText);

            p.executeUpdate();
            p.close();
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error while inserting data into the database.");
        }
    }//GEN-LAST:event_btnDetailPembelianActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter("movie.txt",true));
            out.newLine();
            for(int i=0;i<5;i++)
            {
                out.write(purchasesave[i][0]);
                out.newLine();
            }

            out.close();

            JOptionPane.showMessageDialog(null,"Berhasil");
        }
        catch (IOException e)
        {
            System.out.println("Gagal");
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
         // TODO add your handling code here:
    lblNamaFilm.setText(" ");
    lblJumNo.setText(" ");
    lblTgldanWaktu.setText(" ");
    lblTotalBayar.setText("");
    cmbfilm.setSelectedIndex(0);
    cmbTanggal.setSelectedIndex(0);
    cmbWaktu.setSelectedIndex(0);
    lblTotal.setText("0");
    lblPajak.setText("0");
    lblbayar.setText("0");
    lbljumlahkursi.setText("0");
    
    //enable checboxes again
    enableCheckboxes();

    // Clear checkboxes
    clearCheckboxes();
    
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagihanActionPerformed
        // TODO add your handling code here:
        DecimalFormat formatter = new DecimalFormat("Rp #,##0");
        JOptionPane.showMessageDialog(null,"Total Bayar: "+formatter.format(overralltotalsale));
    }//GEN-LAST:event_btnTagihanActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void chkBoxA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxA1ActionPerformed

    private void chkBoxA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxA2ActionPerformed

    private void chkBoxA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxA3ActionPerformed

    private void chkBoxA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxA4ActionPerformed

    private void chkBoxC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxC5ActionPerformed

    private void chkBoxC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxC6ActionPerformed

    private void chkBoxC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxC7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxC7ActionPerformed

    private void chkBoxB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxB4ActionPerformed

    private void BtnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCekActionPerformed
         System.out.println("Mencheck Kursi...");
         checkBookedSeats();
         System.out.println("Proses Cek Selesai.");
         
          // Count the available chairs and display the count
    int availableChairs = countAvailableChairs();
    lbljumlahkursi.setText(Integer.toString(availableChairs));
    }//GEN-LAST:event_BtnCekActionPerformed

    private void clearCheckboxes() {
    chkBoxA1.setSelected(false);
    chkBoxA2.setSelected(false);
    chkBoxA3.setSelected(false);
    chkBoxA4.setSelected(false);
    chkBoxA5.setSelected(false);
    chkBoxA6.setSelected(false);
    chkBoxA7.setSelected(false);
    chkBoxB1.setSelected(false);
    chkBoxB3.setSelected(false);
    chkBoxB4.setSelected(false);
    chkBoxB2.setSelected(false);
    chkBoxB5.setSelected(false);
    chkBoxB7.setSelected(false);
    chkBoxB6.setSelected(false);
    chkBoxC2.setSelected(false);
    chkBoxC1.setSelected(false);
    chkBoxC3.setSelected(false);
    chkBoxC5.setSelected(false);
    chkBoxC4.setSelected(false);
    chkBoxC6.setSelected(false);
    chkBoxC7.setSelected(false);
}
    
    private void enableCheckboxes() {
    chkBoxA1.setEnabled(true);
    chkBoxA2.setEnabled(true);
    chkBoxA3.setEnabled(true);
    chkBoxA4.setEnabled(true);
    chkBoxA5.setEnabled(true);
    chkBoxA6.setEnabled(true);
    chkBoxA7.setEnabled(true);
    chkBoxB1.setEnabled(true);
    chkBoxB3.setEnabled(true);
    chkBoxB4.setEnabled(true);
    chkBoxB2.setEnabled(true);
    chkBoxB5.setEnabled(true);
    chkBoxB7.setEnabled(true);
    chkBoxB6.setEnabled(true);
    chkBoxC2.setEnabled(true);
    chkBoxC1.setEnabled(true);
    chkBoxC3.setEnabled(true);
    chkBoxC5.setEnabled(true);
    chkBoxC4.setEnabled(true);
    chkBoxC6.setEnabled(true);
    chkBoxC7.setEnabled(true);
 }
    
    // New method to count selected checkboxes
private int countSelectedCheckboxes() {
    int count = 0;

    // Add all your checkboxes to this array
    JCheckBox[] checkboxes = {chkBoxA1, chkBoxA2, chkBoxA3, chkBoxA4, chkBoxA5, chkBoxA6, chkBoxA7,
            chkBoxB1, chkBoxB2, chkBoxB3, chkBoxB4, chkBoxB5, chkBoxB6, chkBoxB7,
            chkBoxC1, chkBoxC2, chkBoxC3, chkBoxC4, chkBoxC5, chkBoxC6, chkBoxC7};

    for (JCheckBox checkbox : checkboxes) {
        if (checkbox.isSelected()) {
            count++;
        }
    }

    return count;
}

// New method to get selected checkbox text
private String getSelectedCheckboxText() {
    StringBuilder selectedText = new StringBuilder();

    // Add all your checkboxes to this array
    JCheckBox[] checkboxes = {chkBoxA1, chkBoxA2, chkBoxA3, chkBoxA4, chkBoxA5, chkBoxA6, chkBoxA7,
            chkBoxB1, chkBoxB2, chkBoxB3, chkBoxB4, chkBoxB5, chkBoxB6, chkBoxB7,
            chkBoxC1, chkBoxC2, chkBoxC3, chkBoxC4, chkBoxC5, chkBoxC6, chkBoxC7};

    for (JCheckBox checkbox : checkboxes) {
        if (checkbox.isSelected()) {
            selectedText.append(checkbox.getText()).append(", ");
        }
    }

    // Remove the trailing comma and space if any
    if (selectedText.length() > 0) {
        selectedText.delete(selectedText.length() - 2, selectedText.length());
    }

    return selectedText.toString();
}


     // Add this new method to initialize the seatCheckboxMap
private void initializeSeatCheckboxMap() {
    seatCheckboxMap = new HashMap<>();
    
    // Row A
    seatCheckboxMap.put("A1", chkBoxA1);
    seatCheckboxMap.put("A2", chkBoxA2);
    seatCheckboxMap.put("A3", chkBoxA3);
    seatCheckboxMap.put("A4", chkBoxA4);
    seatCheckboxMap.put("A5", chkBoxA5);
    seatCheckboxMap.put("A6", chkBoxA6);
    seatCheckboxMap.put("A7", chkBoxA7);
    
    // Row B
    seatCheckboxMap.put("B1", chkBoxB1);
    seatCheckboxMap.put("B2", chkBoxB2);
    seatCheckboxMap.put("B3", chkBoxB3);
    seatCheckboxMap.put("B4", chkBoxB4);
    seatCheckboxMap.put("B5", chkBoxB5);
    seatCheckboxMap.put("B6", chkBoxB6);
    seatCheckboxMap.put("B7", chkBoxB7);
    
    // Row C
    seatCheckboxMap.put("C1", chkBoxC1);
    seatCheckboxMap.put("C2", chkBoxC2);
    seatCheckboxMap.put("C3", chkBoxC3);
    seatCheckboxMap.put("C4", chkBoxC4);
    seatCheckboxMap.put("C5", chkBoxC5);
    seatCheckboxMap.put("C6", chkBoxC6);
    seatCheckboxMap.put("C7", chkBoxC7);
}

// Add this new method to check if seats are already booked
private void checkBookedSeats() {
    // Replace "selectedFilm", "selectedDate", and "selectedTime" with your actual variables
    String selectedFilm = (String) cmbfilm.getSelectedItem();
    String selectedDate = (String) cmbTanggal.getSelectedItem();
    String selectedTime = (String) cmbWaktu.getSelectedItem();
    
    System.out.println("Selected Film: " + selectedFilm);
    System.out.println("Selected Date: " + selectedDate);
    System.out.println("Selected Time: " + selectedTime);

    try {
        Connection conn = KoneksiDB.getKoneksi();
        String sql = "SELECT no_bangku FROM pembelian WHERE film=? AND tanggal=? AND waktu=?";
        PreparedStatement p = conn.prepareStatement(sql);
        p.setString(1, selectedFilm);
        p.setString(2, selectedDate);
        p.setString(3, selectedTime);

        ResultSet rs = p.executeQuery();

        while (rs.next()) {
            String bookedSeat = rs.getString("no_bangku");
            // Disable the checkbox for the booked seat
            disableCheckbox(bookedSeat);
        }
        
        p.close();
        rs.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error saat memasukkan data.");
    }
}

private void disableCheckbox(String seats) {
    // Split the seats string into individual seat values
    String[] seatArray = seats.split(", ");

    // Iterate over each seat and disable the corresponding checkbox
    for (String seat : seatArray) {
        switch (seat) {
            // Seats in Row A
            case "A1":
                chkBoxA1.setEnabled(false);
                break;
            case "A2":
                chkBoxA2.setEnabled(false);
                break;
            case "A3":
                chkBoxA3.setEnabled(false);
                break;
            case "A4":
                chkBoxA4.setEnabled(false);
                break;
            case "A5":
                chkBoxA5.setEnabled(false);
                break;

            // Seats in Row B
            case "B1":
                chkBoxB1.setEnabled(false);
                break;
            case "B2":
                chkBoxB2.setEnabled(false);
                break;
            case "B3":
                chkBoxB3.setEnabled(false);
                break;
            case "B4":
                chkBoxB4.setEnabled(false);
                break;
            case "B5":
                chkBoxB5.setEnabled(false);
                break;

            // Seats in Row C
            case "C1":
                chkBoxC1.setEnabled(false);
                break;
            case "C2":
                chkBoxC2.setEnabled(false);
                break;
            case "C3":
                chkBoxC3.setEnabled(false);
                break;
            case "C4":
                chkBoxC4.setEnabled(false);
                break;
            case "C5":
                chkBoxC5.setEnabled(false);
                break;

            default:
                break;
        }
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        int userId = 0;

        if (userId <= 0) {
            JOptionPane.showMessageDialog(null, "Anda harus Login terlebih dahulu.\nMengalihkan ke form login!");

            // Redirect to the index form
            index indexForm = new index();
            indexForm.setVisible(true);
            
            // Open Login form
            Login loginForm = new Login();
            loginForm.setVisible(true);
        } else {

            // Show the TiketBioskop form for the specified userId
            TiketBioskop tiketBioskop = new TiketBioskop(userId);
            tiketBioskop.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCek;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDetailPembelian;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnTagihan;
    private javax.swing.JButton btnexit;
    private javax.swing.JCheckBox chkBoxA1;
    private javax.swing.JCheckBox chkBoxA2;
    private javax.swing.JCheckBox chkBoxA3;
    private javax.swing.JCheckBox chkBoxA4;
    private javax.swing.JCheckBox chkBoxA5;
    private javax.swing.JCheckBox chkBoxA6;
    private javax.swing.JCheckBox chkBoxA7;
    private javax.swing.JCheckBox chkBoxB1;
    private javax.swing.JCheckBox chkBoxB2;
    private javax.swing.JCheckBox chkBoxB3;
    private javax.swing.JCheckBox chkBoxB4;
    private javax.swing.JCheckBox chkBoxB5;
    private javax.swing.JCheckBox chkBoxB6;
    private javax.swing.JCheckBox chkBoxB7;
    private javax.swing.JCheckBox chkBoxC1;
    private javax.swing.JCheckBox chkBoxC2;
    private javax.swing.JCheckBox chkBoxC3;
    private javax.swing.JCheckBox chkBoxC4;
    private javax.swing.JCheckBox chkBoxC5;
    private javax.swing.JCheckBox chkBoxC6;
    private javax.swing.JCheckBox chkBoxC7;
    private javax.swing.JComboBox<String> cmbTanggal;
    private javax.swing.JComboBox<String> cmbWaktu;
    private javax.swing.JComboBox<String> cmbfilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblJumNo;
    private javax.swing.JLabel lblNamaFilm;
    private javax.swing.JLabel lblPajak;
    private javax.swing.JLabel lblTgldanWaktu;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalBayar;
    private javax.swing.JLabel lblbayar;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lbljumlahkursi;
    private javax.swing.JLabel lblmaindate;
    // End of variables declaration//GEN-END:variables
}
